### PR TITLE
fix(mathjs): updates mathjs to v7 from v3

### LINKED ISSUE #594: Expressions are not working anymore
**Operating system and application version**
 - OS: Ubuntu 20.04
 - Version: 3.17.1

**Describe the bug**
When you enter something into an `expression`, and error is shown in the console.

**To Reproduce**
1. Add a module to a group
2. Click on a property of the module
3. Expand "expression" in the `Input Config`
4. Do any change in the textarea and click outside of it
5. See that there is an error in the console

```js
Worker caught an error: TypeError: Cannot read property 'parse' of undefined
    at compileExpression (expressions.js?8a2f:24)
```

**Expected behavior**
We can change the expression.

**Additional context**
When starting modV in dev-mode, I see this message:

```js
warning  in ./src/application/worker/store/modules/expressions.js
"export 'default' (imported as 'math') was not found in 'mathjs'
```

### PR DESCRIPTION
**Pull request by 2xAA**
fixes #594

### CODE REVIEW

File: src/application/worker/store/modules/expressions.js [hunk 1]
```diff
@@ -17,12 +17,14 @@ const getters = {
 function compileExpression(expression) {
   const scope = { value: 0, time: 0 };
 
+  console.log(math);
```
Comment (TimPietrusky) [inline src/application/worker/store/modules/expressions.js]: Can you please get rid of this?

**Review by TimPietrusky — APPROVED** [review]
Tested and works! Thank you very much ❤️🌈
