### PR TITLE
fix(macos): adds entitlements and function call to request macos media permissions

### LINKED ISSUE #511: Completely fresh install of modV on macOS doesn't request media access
**Operating system and application version**
 - OS: macOS
 - Version 3.9.0

**Describe the bug**
A completely fresh install of modV on macOS doesn't request media access, so audio reactivity is broken.

**To Reproduce**
1. Run this in your terminal to reset the macOS Camera and Microphone security permissions
    * `tccutil reset Microphone && tccutil reset Camera`
2. Open modV
3. See no macOS permissions for Microphone or Camera are being asked of the user

**Expected behavior**
modV is able to access media devices on all OSs.

**Additional context**
Similar issue: https://github.com/electron-userland/electron-builder/issues/5364
Potential fix? https://www.electronjs.org/docs/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos
More info? https://lifesaver.codes/answer/systempreferences-askformediaaccess(mediatype)-causes-app-to-crash-in-macos-mojave

### PR DESCRIPTION
**Pull request by 2xAA**
See #511 for more detail.

fixes #511

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -18,6 +19,14 @@ import store from "./media-manager/store";
 
 const isDevelopment = process.env.NODE_ENV !== "production";
 
+// We need to ask macOS permission to access media devices
+async function getMediaPermission() {
+  await systemPreferences.askForMediaAccess("microphone");
```
Comment (TimPietrusky) [inline src/background.js]: We should only do this for MacOS and also check the result to provide a message to the end-user (as you suggested) and not just take this for granted. 

Taking the code from https://lifesaver.codes/answer/systempreferences-askformediaaccess(mediatype)-causes-app-to-crash-in-macos-mojave

```javascript
async function askForMediaAccess(): Promise<boolean> {
  try {
    if (platform !== "darwin") {
      return true;
    }

    const status = await systemPreferences.getMediaAccessStatus("microphone");
    log.info("Current microphone access status:", status);

    if (status === "not-determined") {
      const success = await systemPreferences.askForMediaAccess("microphone");
      log.info("Result of microphone access:", success.valueOf() ? "granted" : "denied");
      return success.valueOf();
    }

    return status === "granted";
  } catch (error) {
    log.error("Could not get microphone permission:", error.message);
  }
  return false;
}
```

**Review by TimPietrusky — CHANGES_REQUESTED** [review]
We should not just ask for permission for any system but only for MacOS and also make sure that we provide a message if permission is not granted.

File: src/background.js (hunk 1 above)
Comment (2xAA) [reply src/background.js]: Thanks @TimPietrusky.

The only other thing I would say is that we might need to check Windows 10 media access status too as it's possible media access was restricted at a global system level according to the Electron docs:

https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-windows-macos

But we can split the functionality per platform quite easily.

File: src/background.js [hunk 2]
```diff
@@ -18,6 +19,49 @@ import store from "./media-manager/store";
 
 const isDevelopment = process.env.NODE_ENV !== "production";
 
+// We need to ask macOS permission to access media devices
+async function getMediaPermission() {
+  let accessGranted = false;
+
+  accessGranted = await systemPreferences.askForMediaAccess("microphone");
+  accessGranted = await systemPreferences.askForMediaAccess("camera");
```
Comment (TimPietrusky) [inline src/background.js]: Whem `microphone` is not allowed, but `camera` is allowed, then this will still return `true`, even when we have no access to the `microphone` or am I wrong?

File: src/background.js [hunk 3]
```diff
@@ -18,6 +19,49 @@ import store from "./media-manager/store";
 
 const isDevelopment = process.env.NODE_ENV !== "production";
 
+// We need to ask macOS permission to access media devices
+async function getMediaPermission() {
```
Comment (TimPietrusky) [inline src/background.js]: I would move this function underneath the `checkMediaPermission` as it would be nice when you read the code and the call order is also represented in the code order.

File: src/background.js [hunk 4]
```diff
@@ -18,6 +19,49 @@ import store from "./media-manager/store";
...
+
+  if (
+    (platform === "win32" && !hasMediaPermission) ||
+    (platform === "darwin" && !macOSMediaDialogsAccepted)
+  ) {
+    dialog.showMessageBox({
+      type: "warning",
+      message: "modV does not have access to camera or microphone",
+      detail:
+        "While modV can still be used without these permissions, some functionality will be limited or broken. Please close modV, update your Security permissions and start modV again."
```
Comment (TimPietrusky) [inline src/background.js:50]: In here I would refer to a specific help guide in the modV documentation (which doesn't exist yet) with steps someone might do if this is happening. And it would also be nice if we would know if it's the camera or the microphone, so the debugging can happen more specific.

**Review by TimPietrusky — CHANGES_REQUESTED** [review]
I have 3 change requests!

**Comment by KevinGimbel** [comment]
I just build the version from this PR on MacOS 10.15.7 and it's working for me!

File: src/background.js (hunk 2 above)
Comment (2xAA) [reply src/background.js]: Ah yes, you're right. My bad!

File: src/background.js (hunk 4 above)
Comment (2xAA) [reply src/background.js:50]: Can we create a new PR when we have the documentation, or do we want to wait until we have these docs?

Comment (TimPietrusky) [reply src/background.js:50]: We can do this in a new PR.

**Review by TimPietrusky — APPROVED** [review]
LGTM, thank you @2xAA  <3
