### PR TITLE
fix(imageControl): Fix image control for 2.0-drawloop

### LINKED ISSUE #218: Fix Image Control

### PR DESCRIPTION
**Pull request by 2xAA**
Fixes #218

### CODE REVIEW

File: src/components/ControlPanel/ImageControl.vue [hunk 1]
```diff
@@ -60,37 +84,54 @@
...
+      label() {
+        return this.meta.label || this.variable;
       },
       moduleName() {
-        return this.module.info.name;
+        return this.meta.$modv_moduleName;
       },
-      variable() {
-        return this.control.variable;
+      // value() {
```
Comment (TimPietrusky) [inline src/components/ControlPanel/ImageControl.vue]: Can we get rid of this?

**Review by TimPietrusky — CHANGES_REQUESTED** [review]
Can we get rid of the commented code?

File: src/components/ControlPanel/ImageControl.vue (hunk 1 above)
Comment (2xAA) [reply src/components/ControlPanel/ImageControl.vue]: Sure thing. Change incoming!

**Review by TimPietrusky — APPROVED** [review]
