### PR TITLE
fix(image): fixes texture initialisation

### LINKED ISSUE #706: Texture 2D is not showing an "image" anymore
**Operating system and application version**
 - OS: macOS
 - Version: next

**Describe the bug**
When using `Texture 2D` > `image`, the image is not shown anymore. 

**To Reproduce**
1. Add `Texture 2D`
2. Select `image`
3. Select any image
4. See that the image is not shown

**Expected behavior**
The image is shown. 

**Additional context**
When testing https://github.com/vcync/modV/pull/655 it was still working, but then I was checking another PR and saw that the same bug occurred. My first intention was that this was related to the PR https://github.com/vcync/modV/pull/657, but then I also saw this error in another PR and tested it in `next`. And there was the same problem.

### PR DESCRIPTION
**Pull request by 2xAA**
Not entirely sure of the semantic difference here? There is one, but I need to deconstruct it before I properly understand.

fixes #706

### CODE REVIEW

File: src/application/worker/store/modules/dataTypes.js [hunk 1]
```diff
@@ -37,9 +37,11 @@ const state = {
         const { path } = options;
         let id;
         try {
-          id = await store.dispatch("images/createImageFromPath", {
+          const image = await store.dispatch("images/createImageFromPath", {
             path
-          }).id;
+          });
+
+          id = image.id;
```
Comment (TimPietrusky) [inline src/application/worker/store/modules/dataTypes.js]: `({ id } = await store.dispatch("images/createImageFromPath", {
            path
 }))`

**Comment by TimPietrusky** [comment]
@2xAA I have just one tiny change 🙏

**Review by TimPietrusky — CHANGES_REQUESTED** [review]
I think you could do this more elegant!

**Comment by TimPietrusky** [comment]
Awesome, works! Thank you!
